// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: idgen/v1/sequence.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sequence_Next_FullMethodName = "/api.idgen.v1.Sequence/Next"
)

// SequenceClient is the client API for Sequence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SequenceClient interface {
	Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error)
}

type sequenceClient struct {
	cc grpc.ClientConnInterface
}

func NewSequenceClient(cc grpc.ClientConnInterface) SequenceClient {
	return &sequenceClient{cc}
}

func (c *sequenceClient) Next(ctx context.Context, in *NextRequest, opts ...grpc.CallOption) (*NextReply, error) {
	out := new(NextReply)
	err := c.cc.Invoke(ctx, Sequence_Next_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SequenceServer is the server API for Sequence service.
// All implementations must embed UnimplementedSequenceServer
// for forward compatibility
type SequenceServer interface {
	Next(context.Context, *NextRequest) (*NextReply, error)
	mustEmbedUnimplementedSequenceServer()
}

// UnimplementedSequenceServer must be embedded to have forward compatible implementations.
type UnimplementedSequenceServer struct {
}

func (UnimplementedSequenceServer) Next(context.Context, *NextRequest) (*NextReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedSequenceServer) mustEmbedUnimplementedSequenceServer() {}

// UnsafeSequenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SequenceServer will
// result in compilation errors.
type UnsafeSequenceServer interface {
	mustEmbedUnimplementedSequenceServer()
}

func RegisterSequenceServer(s grpc.ServiceRegistrar, srv SequenceServer) {
	s.RegisterService(&Sequence_ServiceDesc, srv)
}

func _Sequence_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SequenceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sequence_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SequenceServer).Next(ctx, req.(*NextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sequence_ServiceDesc is the grpc.ServiceDesc for Sequence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sequence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.idgen.v1.Sequence",
	HandlerType: (*SequenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Next",
			Handler:    _Sequence_Next_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "idgen/v1/sequence.proto",
}
