// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"idgen/internal/biz"
	"idgen/internal/conf"
	"idgen/internal/data"
	"idgen/internal/server"
	"idgen/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewEtcdClient(confData, logger)
	node := data.NewSnowflakeNode(client, logger)
	dataData, cleanup, err := data.NewData(client, node, logger)
	if err != nil {
		return nil, nil, err
	}
	sequenceRepo := data.NewSequenceRepo(dataData, logger)
	sequenceUsecase := biz.NewSequenceUsecase(sequenceRepo, logger)
	sequenceService := service.NewSequenceService(sequenceUsecase)
	snowflakeRepo := data.NewSnowflakeRepo(dataData, logger)
	snowflakeUsecase := biz.NewSnowflakeUsecase(snowflakeRepo, logger)
	snowflakeService := service.NewSnowflakeService(snowflakeUsecase)
	grpcServer := server.NewGRPCServer(confServer, logger, sequenceService, snowflakeService)
	httpServer := server.NewHTTPServer(confServer, logger, sequenceService, snowflakeService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
